### ISSUE TITLE
GitHub removed support for anonymous gists

### ISSUE THREAD

**Issue by chesterharvey** [jwass/geojsonio.py#11]
I kept getting `GitHubError: 422 Validation Failed` from `github3.py` when running `geojsonio.display(json, force_gist=True)`. Then I found [issue 795](https://github.com/sigmavirus24/github3.py/issues/795) on the github3.py repo. Are there any plans already in the works to pass GitHub account info for pushing geojsons to authorized gists?

**Comment by zneu** [comment]
Similar issue:

```
     35                 '{"message": "Requires authentication"}'
     36             )
---> 37             raise error_for(r)
     38     return auth_wrapper
     39 

AuthenticationFailed: 401 Requires authentication
```

**Comment by tomjm1** [comment]
Even I face the same:

https://stackoverflow.com/questions/50192549/display-in-geojsonio-gives-401-error

**Comment by nittolese** [comment]
I have the same issue with `geojsonio.display(file, force_gist=True)`

Please update with alternatives to anonymous gist as they have been deprecated: https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/

**Comment by jwass** [comment]
I suppose the right way to fix this is to initialize a github3 API object and pass it in to `.display()`.

**Comment by HADDADENICAR** [comment]
Same problem here ?
jwass could you please explain more  how to do that !?

**Comment by medeirosjoaquim** [comment]
try this:
install github3.py
`$pip3 install github3.py`  

and, in your project:

`from github3 import login
gh = login('<USERNAME>', password='<PASS>')`

**Comment by Graygood** [comment]
same here

Worked yesterday like a charm
