### ISSUE TITLE
Privacy issue: Gists posted without warning

### ISSUE THREAD

**Issue by freeatnet** [jwass/geojsonio.py#4]
Could you please make a mention of the gem posting data publicly on GitHub somewhere?

**Comment by jwass** [comment]
Thanks @freeatnet.

I just added a more detailed explanation in the Readme. Can you take a look and let me know if you think this suffices? If it does, feel free to close the issue. Otherwise let me know what's missing, or create a pull request with some suggestions of better wording.

**Comment by freeatnet** [comment]
Looks good for the wording.

Would you be interested in a feature allowing to pass github authentication token for gist creation?
